-- Your SQL goes here
CREATE TABLE companies (
    id SERIAL PRIMARY KEY, 
    company_name VARCHAR(50) NOT NULL,
    industry VARCHAR(50) NOT NULL,
    isin VARCHAR(12) NOT NULL,
    exchange VARCHAR(9) NOT NULL,
    ticker VARCHAR(6) NOT NULL,
    last_updated DATE NOT NULL,
    UNIQUE(isin)
);

CREATE TABLE forecasts(
    id SERIAL PRIMARY KEY,
    company_id INTEGER REFERENCES companies(id) NOT NULL,
    next_earnings_date DATE,
    latest_price DOUBLE PRECISION,
    last_updated DATE,
    revenue_next_year DOUBLE PRECISION,
    revenue_growth_next_year DOUBLE PRECISION,
    price_current_revenue_growth DOUBLE PRECISION,
    price_current_gp_growth DOUBLE PRECISION,
    price_next_year_revenue_growth DOUBLE PRECISION,
    price_multi_year_revenue_growth DOUBLE PRECISION,
    price_multi_year_gp_growth DOUBLE PRECISION,
    UNIQUE(company_id)
);

CREATE TABLE current_metrics (
    id SERIAL PRIMARY KEY,
    company_id INTEGER REFERENCES companies(id) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    net_interest_income_growth_yoy_ttm DOUBLE PRECISION,
    net_interest_income_growth_multi_year DOUBLE PRECISION,
    net_interest_margin_ttm DOUBLE PRECISION,
    net_interest_margin_short_term_trend TEXT,
    net_interest_margin_long_term_trend TEXT,
    cost_of_risk_ttm DOUBLE PRECISION,
    cost_of_risk_short_term_trend TEXT,
    cost_of_risk_long_term_trend TEXT,
    revenue_ttm DOUBLE PRECISION,
    revenue_growth_yoy_ttm DOUBLE PRECISION,
    revenue_growth_multi_year DOUBLE PRECISION,
    gross_profit_growth_yoy_ttm DOUBLE PRECISION,
    gross_profit_growth_multi_year DOUBLE PRECISION,
    gross_margin_ttm DOUBLE PRECISION,
    gross_margin_short_term_trend TEXT,
    gross_margin_long_term_trend TEXT,
    sga_ratio_ttm DOUBLE PRECISION,
    sga_short_term_trend TEXT,
    sga_long_term_trend TEXT,
    rnd_ratio_ttm DOUBLE PRECISION,
    rnd_short_term_trend TEXT,
    rnd_long_term_trend TEXT,
    operating_margin_ttm DOUBLE PRECISION,
    operating_margin_short_term_trend TEXT,
    operating_margin_long_term_trend TEXT,
    interest_expense_ratio_ttm DOUBLE PRECISION,
    net_margin_ttm DOUBLE PRECISION,
    theoretical_net_margin DOUBLE PRECISION,
    is_net_margin_optimized BOOLEAN,
    shares_outstanding_diluted_ttm DOUBLE PRECISION,
    shares_change_ttm DOUBLE PRECISION,
    shares_change_multi_year DOUBLE PRECISION,
    shares_change_trend TEXT,
    retained_earnings_ttm DOUBLE PRECISION,
    retained_earnings_trend TEXT,
    net_cash_ttm DOUBLE PRECISION,
    has_healthy_net_cash BOOLEAN,
    net_cash_trend TEXT,
    operating_cash_flow_ttm DOUBLE PRECISION,
    operating_cash_flow_margin_ttm DOUBLE PRECISION,
    operating_cash_flow_margin_trend TEXT,
    free_cash_flow_ttm DOUBLE PRECISION,
    free_cash_flow_margin_ttm DOUBLE PRECISION,
    ffo_margin_ttm DOUBLE PRECISION,
    ffo_margin_trend TEXT,
    
    UNIQUE(company_id)
);

CREATE TABLE earnings_report (
    id SERIAL PRIMARY KEY,
    company_id INTEGER REFERENCES companies(id) NOT NULL,
    duration VARCHAR(1) NOT NULL,
    quarter_str SMALLINT NOT NULL,
    year_str SMALLINT NOT NULL,
    period_ending DATE NOT NULL,
    currency VARCHAR(3) NOT NULL,
    net_interest_income DOUBLE PRECISION,
    net_interest_growth_yoy DOUBLE PRECISION,
    net_interest_margin DOUBLE PRECISION,
    provision_for_loan_loss DOUBLE PRECISION,
    cost_of_risk DOUBLE PRECISION,
    revenue DOUBLE PRECISION NOT NULL,
    revenue_growth_yoy DOUBLE PRECISION,
    cost_of_revenue DOUBLE PRECISION,
    gross_profit DOUBLE PRECISION,
    gross_margin DOUBLE PRECISION,
    gross_profit_growth_yoy DOUBLE PRECISION,
    sga_expenses DOUBLE PRECISION,
    sga_gp_ratio DOUBLE PRECISION,
    rnd_expenses DOUBLE PRECISION,
    rnd_gp_ratio DOUBLE PRECISION,
    operating_expenses DOUBLE PRECISION NOT NULL,
    operating_income DOUBLE PRECISION NOT NULL,
    operating_margin DOUBLE PRECISION NOT NULL,
    interest_expenses DOUBLE PRECISION,
    interest_expenses_op_income_ratio DOUBLE PRECISION,
    goodwill_impairment DOUBLE PRECISION NOT NULL,
    net_income DOUBLE PRECISION NOT NULL,
    net_margin DOUBLE PRECISION NOT NULL,
    eps_basic DOUBLE PRECISION NOT NULL,
    eps_diluted DOUBLE PRECISION NOT NULL,
    shares_outstanding_basic DOUBLE PRECISION NOT NULL,
    shares_outstanding_diluted DOUBLE PRECISION NOT NULL,
    shares_change_yoy DOUBLE PRECISION NOT NULL,
    ffo DOUBLE PRECISION,
    ffo_margin DOUBLE PRECISION,
    cash_and_equivalents DOUBLE PRECISION NOT NULL,
    cash_and_short_term_investments DOUBLE PRECISION,
    total_investments DOUBLE PRECISION,
    gross_loans DOUBLE PRECISION,
    accounts_receivable DOUBLE PRECISION,
    inventory DOUBLE PRECISION,
    total_current_assets DOUBLE PRECISION,
    goodwill DOUBLE PRECISION,
    total_assets DOUBLE PRECISION NOT NULL,
    accounts_payable DOUBLE PRECISION,
    total_current_liabilities DOUBLE PRECISION,
    total_liabilities DOUBLE PRECISION NOT NULL,
    retained_earnings  DOUBLE PRECISION NOT NULL,
    shareholders_equity DOUBLE PRECISION NOT NULL,
    total_debt DOUBLE PRECISION,
    net_cash DOUBLE PRECISION NOT NULL,
    depreciation_and_amortization DOUBLE PRECISION,
    stock_based_compensation DOUBLE PRECISION,
    operating_cash_flow DOUBLE PRECISION,
    operating_cash_flow_margin DOUBLE PRECISION,
    capital_expenditure DOUBLE PRECISION,
    investing_cash_flow DOUBLE PRECISION,
    financing_cash_flow DOUBLE PRECISION,
    free_cash_flow DOUBLE PRECISION,
    free_cash_flow_margin DOUBLE PRECISION,
    ratio_calculated BOOLEAN NOT NULL,
    growth_calculated BOOLEAN NOT NULL,
    UNIQUE (company_id, duration, quarter_str, year_str)
);
