-- up

CREATE TABLE stock_data (
    id SERIAL PRIMARY KEY,
    exchange VARCHAR(9) NOT NULL,
    ticker VARCHAR(6) NOT NULL,
    duration VARCHAR(1) NOT NULL,
    quarter_str SMALLSERIAL NOT NULL,
    year_str SMALLSERIAL NOT NULL,
    revenue DOUBLE PRECISION NOT NULL,
    revenue_growth_yoy DOUBLE PRECISION NOT NULL,
    cost_of_revenue DOUBLE PRECISION,
    gross_profit DOUBLE PRECISION,
    gross_margin DOUBLE PRECISION,
    gross_profit_growth_yoy DOUBLE PRECISION,
    sga_expenses DOUBLE PRECISION,
    sga_gp_ratio DOUBLE PRECISION,
    rnd_expenses DOUBLE PRECISION,
    rnd_gp_ratio DOUBLE PRECISION,
    operating_expenses DOUBLE PRECISION NOT NULL,
    operating_income DOUBLE PRECISION NOT NULL,
    operating_margin DOUBLE PRECISION NOT NULL,
    interest_expenses DOUBLE PRECISION,
    interest_expenses_op_income_ratio DOUBLE PRECISION,
    net_income DOUBLE PRECISION NOT NULL,
    net_margin DOUBLE PRECISION NOT NULL,
    eps_basic DOUBLE PRECISION NOT NULL,
    eps_diluted DOUBLE PRECISION NOT NULL,
    shares_outstanding_basic DOUBLE PRECISION NOT NULL,
    shares_outstanding_diluted DOUBLE PRECISION NOT NULL,
    shares_change_yoy DOUBLE PRECISION NOT NULL,
    cash_and_equivalents DOUBLE PRECISION NOT NULL,
    cash_and_short_term_investments DOUBLE PRECISION NOT NULL,
    accounts_receivable DOUBLE PRECISION NOT NULL,
    inventory DOUBLE PRECISION NOT NULL,
    total_current_assets DOUBLE PRECISION NOT NULL,
    goodwill DOUBLE PRECISION NOT NULL,
    total_assets DOUBLE PRECISION NOT NULL,
    accounts_payable DOUBLE PRECISION NOT NULL,
    total_current_liabilities DOUBLE PRECISION NOT NULL,
    total_liabilities DOUBLE PRECISION NOT NULL,
    retained_earnings  DOUBLE PRECISION NOT NULL,
    shareholders_equity DOUBLE PRECISION NOT NULL,
    total_debt DOUBLE PRECISION NOT NULL,
    net_cash DOUBLE PRECISION NOT NULL,
    depreciation_and_amortization DOUBLE PRECISION NOT NULL,
    stock_based_compensation DOUBLE PRECISION NOT NULL,
    operating_cash_flow DOUBLE PRECISION NOT NULL,
    capital_expenditure DOUBLE PRECISION NOT NULL,
    investing_cash_flow DOUBLE PRECISION NOT NULL,
    financing_cash_flow DOUBLE PRECISION NOT NULL,
    free_cash_flow DOUBLE PRECISION NOT NULL,
    free_cash_flow_margin DOUBLE PRECISION NOT NULL,
    ratio_calculated BOOLEAN NOT NULL,
    growth_calculated BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX same_earning ON stock_data (exchange, ticker, duration, quarter_str, year_str);