// @generated automatically by Diesel CLI.

diesel::table! {
    stock_data (id) {
        id -> Int4,
        #[max_length = 9]
        exchange -> Varchar,
        #[max_length = 6]
        ticker -> Varchar,
        #[max_length = 1]
        duration -> Varchar,
        quarter_str -> Int2,
        year_str -> Int2,
        revenue -> Float8,
        revenue_growth_yoy -> Float8,
        cost_of_revenue -> Nullable<Float8>,
        gross_profit -> Nullable<Float8>,
        gross_margin -> Nullable<Float8>,
        gross_profit_growth_yoy -> Nullable<Float8>,
        sga_expenses -> Nullable<Float8>,
        sga_gp_ratio -> Nullable<Float8>,
        rnd_expenses -> Nullable<Float8>,
        rnd_gp_ratio -> Nullable<Float8>,
        operating_expenses -> Float8,
        operating_income -> Float8,
        operating_margin -> Float8,
        interest_expenses -> Nullable<Float8>,
        interest_expenses_op_income_ratio -> Nullable<Float8>,
        net_income -> Float8,
        net_margin -> Float8,
        eps_basic -> Float8,
        eps_diluted -> Float8,
        shares_outstanding_basic -> Float8,
        shares_outstanding_diluted -> Float8,
        shares_change_yoy -> Float8,
        cash_and_equivalents -> Float8,
        cash_and_short_term_investments -> Float8,
        accounts_receivable -> Float8,
        inventory -> Float8,
        total_current_assets -> Float8,
        goodwill -> Float8,
        total_assets -> Float8,
        accounts_payable -> Float8,
        total_current_liabilities -> Float8,
        total_liabilities -> Float8,
        retained_earnings -> Float8,
        shareholders_equity -> Float8,
        total_debt -> Float8,
        net_cash -> Float8,
        depreciation_and_amortization -> Float8,
        stock_based_compensation -> Float8,
        operating_cash_flow -> Float8,
        capital_expenditure -> Float8,
        investing_cash_flow -> Float8,
        financing_cash_flow -> Float8,
        free_cash_flow -> Float8,
        free_cash_flow_margin -> Float8,
        ratio_calculated -> Bool,
        growth_calculated -> Bool,
    }
}

diesel::table! {
    stock_health_eval (id) {
        id -> Int4,
        #[max_length = 9]
        exchange -> Varchar,
        #[max_length = 6]
        ticker -> Varchar,
        #[max_length = 3]
        currency -> Varchar,
        favorite -> Bool,
        #[max_length = 50]
        industry -> Varchar,
        next_earnings_date -> Nullable<Date>,
        latest_price -> Nullable<Float8>,
        positive_operating_cash_flow -> Nullable<Bool>,
        operating_cash_flow_health -> Nullable<Bool>,
        improving_gross_margin -> Nullable<Bool>,
        low_customer_acquisition -> Nullable<Bool>,
        improving_customer_acquisition -> Nullable<Bool>,
        low_innovation -> Nullable<Bool>,
        improving_innovation -> Nullable<Bool>,
        low_interest_burden -> Nullable<Bool>,
        healthy_net_cash -> Nullable<Bool>,
        positive_retained_earnings -> Nullable<Bool>,
        improving_retained_earnings -> Nullable<Bool>,
        no_share_dilution -> Nullable<Bool>,
        improving_share_dilution -> Nullable<Bool>,
        latest_revenue -> Nullable<Float8>,
        revenue_next_year -> Nullable<Float8>,
        revenue_growth_1y -> Nullable<Float8>,
        revenue_growth_multi_year -> Nullable<Float8>,
        revenue_growth_next_year -> Nullable<Float8>,
        gross_profit_growth_1y -> Nullable<Float8>,
        gross_profit_growth_multi_year -> Nullable<Float8>,
        latest_gross_margin -> Nullable<Float8>,
        latest_operating_margin -> Nullable<Float8>,
        latest_net_margin -> Nullable<Float8>,
        latest_eps -> Nullable<Float8>,
        latest_operating_cash_flow -> Nullable<Float8>,
        latest_free_cash_flow -> Nullable<Float8>,
        theoretical_net_margin -> Nullable<Float8>,
        theoretical_net_income -> Nullable<Float8>,
        theoretical_net_income_next_year -> Nullable<Float8>,
        optimized_net_margin -> Nullable<Bool>,
        price_current_revenue_growth -> Nullable<Float8>,
        price_current_gp_growth -> Nullable<Float8>,
        price_next_year_revenue_growth -> Nullable<Float8>,
        price_multi_year_revenue_growth -> Nullable<Float8>,
        price_multi_year_gp_growth -> Nullable<Float8>,
        last_updated -> Nullable<Date>,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    stock_data,
    stock_health_eval,
);
